name: CD

on:
  push:
    tags: '*'

jobs:
  build-lin:
    name: Linux Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: { fetch-depth: 0 }
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-10-multilib
      - name: Build
        env:
          RELEASE_BUILD: 1
        run: make -j$(nproc)
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: wormhole-linux
          path: wormhole.so
          if-no-files-found: error
  build-win:
    name: Windows Build
    runs-on: windows-2019
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: { fetch-depth: 0 }
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        env:
          RELEASE_BUILD: 1
        run: msbuild -m -t:wormhole -p:"Configuration=Release;Platform=x86" wormhole.sln
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: wormhole-windows
          path: bin\wormhole.dll
          if-no-files-found: error
      - name: Upload PDB Artifact
        uses: actions/upload-artifact@v3
        with:
          name: wormhole-windows-pdb
          path: bin\wormhole.pdb
          if-no-files-found: error
  release:
    name: Release
    if: github.repository == 'Zyntex1/wormhole'
    needs: [build-lin, build-win]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux Build
        uses: actions/download-artifact@v3
        with:
          name: wormhole-linux
      - name: Download Windows Build
        uses: actions/download-artifact@v3
        with:
          name: wormhole-windows
      - name: Download Windows PDB
        uses: actions/download-artifact@v3
        with:
          name: wormhole-windows-pdb
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ![CD](https://github.com/Zyntex1/wormhole/workflows/CD/badge.svg)

            **Installation**
            - Place the binary into the game folder e.g. `Portal 2`
            - Open developer console and enter `plugin_load wormhole`

            ---

            **Changelog**
            TODO
          files: |
            wormhole.so
            wormhole.dll
            wormhole.pdb
          prerelease: ${{ contains(github.ref, '-pre') }}
          fail_on_unmatched_files: true
